#!/usr/bin/env bash

SCRIPT_PATH=$(readlink -f "$0")
USER=vortex
BASE_DIR="$HOME/.pikdum/vortex"
WINE_BUILDS="$BASE_DIR/wine-builds"
VORTEX_INSTALLERS="$BASE_DIR/vortex-installers"
VORTEX_PREFIX="$BASE_DIR/vortex-prefix"

# create required folders
setup() {
    mkdir -p "$WINE_BUILDS" "$VORTEX_INSTALLERS" "$VORTEX_PREFIX"
}

# get asset url from latest github release
# params: $1 - github repo, $2 - file extension
get_latest_release() {
    local repo="$1"
    local ext="$2"
    echo "Looking up latest $repo $ext asset..." >&2
    curl -# -L "https://api.github.com/repos/$repo/releases/latest" | grep -o "https://.*${ext}"
}

# download latest wine-ge-custom
download_wine() {
    cd "$WINE_BUILDS"
    url="$(get_latest_release "GloriousEggroll/wine-ge-custom" ".tar.xz")"
    filename="$(basename -- "$url")"
    echo "Downloading $filename..." >&2
    curl -# -L "$url" | tar -xJ
}

# download latest vortex setup exe
download_vortex() {
    cd "$VORTEX_INSTALLERS"
    local url="$(get_latest_release "Nexus-Mods/Vortex" ".exe")"
    local filename="$(basename -- "$url")"
    echo "Downloading $filename..." >&2
    rm -f "$filename"
    curl -# -OJL "$url"
}

# download the latest vortexgames.txt mapping
# used to find which games map to which proton prefixes
download_mapping() {
    cd "$BASE_DIR"
    echo "Downloading vortexgames.txt mapping..." >&2
    curl -# -OJL "https://raw.githubusercontent.com/sonic2kk/steamtinkerlaunch/master/misc/vortexgames.txt"
}

# create vortex's wineprefix
setup_wineprefix() {
    echo "Setting up WINEPREFIX: $VORTEX_PREFIX..." >&2

    WINE_BUILD="$WINE_BUILDS/$(select_from_folder "$WINE_BUILDS" "Choose a Wine build: ")"
    trap '$WINE_BUILD/bin/wineserver --kill' EXIT

    WINEDLLOVERRIDES="mscoree,mshtml=" WINEPREFIX="$VORTEX_PREFIX" "$WINE_BUILD/bin/wineboot" --init
    WINEPREFIX="$VORTEX_PREFIX" "$WINE_BUILD/bin/wineserver" --wait

    # remove symlinks, because why are they even there
    for item in "$VORTEX_PREFIX/drive_c/users/vortex"/*; do
    if [ -h "$item" ]; then
        rm "$item"
        mkdir "$item"
    fi
    done
}

# mount some steam game folders as windows drives
setup_drives() {
    echo "Setting up drives..."
    cd "$VORTEX_PREFIX/dosdevices"
    ln -s $HOME/.steam/steam/steamapps/common/ d: || true
    # TODO: set up steam deck sd card
}

# select item from folder
# params: $1 - folder, $2 - prompt
select_from_folder() {
    local directory="$1"
    local prompt="$2"
    local options=()

    for option in "$directory"/*; do
        options+=("$(basename "$option")")
    done

    if [[ ${#options[@]} -eq 1 ]]; then
        echo "${options[0]}"
        return
    fi

    PS3="$prompt"
    select dir in "${options[@]}"; do
        if [[ -n $dir ]]; then
            echo "$dir"
            return
        else
            echo "Invalid selection, try again." >&2
        fi
    done
}

# select an installed game
select_game_id() {
    local compatdata_dir="$HOME/.steam/steam/steamapps/compatdata"
    local vortexgames_file="$BASE_DIR/vortexgames.txt"

    # Get a list of all game IDs from subfolders in $compatdata_dir
    local game_ids=()
    for folder in "$compatdata_dir"/*; do
        if [[ -d "$folder" ]]; then
            game_ids+=("$(basename "$folder")")
        fi
    done

    # Filter out lines from vortexgames.txt that don't have subfolders
    local filtered_lines=()
    while IFS=';' read -r slug name id; do
        id="${id//\"/}"  # Remove quotes from game ID
        name="${name//\"/}"  # Remove quotes from game name
        if [[ "${game_ids[*]}" =~ (^|[[:space:]])$id($|[[:space:]]) ]]; then
            filtered_lines+=("$name [$id]")
        fi
    done < "$vortexgames_file"


    # Show a bash select menu with game options
    PS3="Select a game: "
    select option in "${filtered_lines[@]}"; do
        if [[ -n $option ]]; then
            # Extract the game ID from the selected option
            local game_id="${option##*[}"
            game_id="${game_id%]}"
            echo "$game_id"
            return
        else
            echo "Invalid selection, try again."
        fi
    done
}

# add a .desktop entry to ~/.local/share/applications/
# can use this for opening nxm:// links
install_desktop_entry() {
    echo "Downloading icon..." >&2
    rm -f "$BASE_DIR/vortex.ico"
    curl -# -JL -o "$BASE_DIR/vortex.ico" "https://raw.githubusercontent.com/pikdum/vortex-linux/master/assets/vortex.ico"

    echo "Creating .desktop entry..."
cat <<EOF > "$HOME/.local/share/applications/vortex-linux.desktop"
[Desktop Entry]
Type=Application
Categories=Game;Utility
Name=Vortex
MimeType=x-scheme-handler/nxm;x-scheme-handler/nxm-protocol
Terminal=false
X-KeepTerminal=false
Path=$HOME/.pikdum/vortex/vortex-prefix/drive_c/Program Files/Black Tree Gaming Ltd/Vortex
Exec=$SCRIPT_PATH start -d %u
Icon=$HOME/.pikdum/vortex/vortex.ico
EOF
    gtk-update-icon-cache || true
}

# run vortex setup exe
install_vortex() {
    echo "Installing Vortex..." >&2

    WINE_BUILD="$WINE_BUILDS/$(select_from_folder "$WINE_BUILDS" "Choose a Wine build: ")"
    trap '$WINE_BUILD/bin/wineserver --kill' EXIT

    local vortex_exe="$VORTEX_INSTALLERS/$(select_from_folder "$VORTEX_INSTALLERS" "Choose a Vortex version: ")"

    install_desktop_entry
    WINEPREFIX="$VORTEX_PREFIX" "$WINE_BUILD/bin/wine" "$vortex_exe"
    WINEPREFIX="$VORTEX_PREFIX" "$WINE_BUILD/bin/wineserver" --wait
}

# start vortex
start_vortex() {
    echo "Starting Vortex..." >&2

    # TODO: rather than asking every time (if multiple), should be able to set a 'default'
    WINE_BUILD="$WINE_BUILDS/$(select_from_folder "$WINE_BUILDS" "Choose a Wine build: ")"

    if [ "$1" = "-d" ] || [ "$1" = "-i" ]; then
        if [ -n "$2" ]; then
            # url supplied, so pass arguments to vortex
            WINEPREFIX="$VORTEX_PREFIX" "$WINE_BUILD/bin/wine" "$VORTEX_PREFIX/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe" "$@"
        else
            # no url supplied, so do not pass arguments
            # this so so we can always have a trailing -i or -d in the .desktop file, without errors
            WINEPREFIX="$VORTEX_PREFIX" "$WINE_BUILD/bin/wine" "$VORTEX_PREFIX/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe"
        fi
    else
        # not install, so pass args
        WINEPREFIX="$VORTEX_PREFIX" "$WINE_BUILD/bin/wine" "$VORTEX_PREFIX/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/Vortex.exe" "$@"
    fi

}

# begin of more important commands

# set up dependencies + install vortex
install() {
    setup
    download_wine
    download_vortex
    download_mapping
    setup_wineprefix
    setup_drives
    install_vortex
}

# uninstall this tool
uninstall() {
    rm -rf "$BASE_DIR"
    rm -rf "$HOME/.local/share/applications/vortex-linux.desktop"
    echo "Vortex uninstalled." &>2
}

# start vortex
start() {
    start_vortex "$@"
}

# pull new wine and vortex versions
# and game mappings
update() {
    echo "Grabbing new releases..."
    setup
    download_wine
    download_vortex
    download_mapping
}

# this will go through the target game's home directory, recursively,
# and symlink folders to vortex's home directory
# this is mostly to support bethesda games,
# since they keep loadorder.txt and plugins.txt in appdata
# but might be flexible enough for others that do similar
symlink() {
    echo "Symlinking target game's home subfolders to Vortex..."
    local game_id="$(select_game_id)"
    local compatdata_dir="$HOME/.steam/steam/steamapps/compatdata"
    local src_dir="$compatdata_dir/$game_id/pfx/drive_c/users/steamuser"
    local dest_dir="$VORTEX_PREFIX/drive_c/users/vortex"

    # Check if the source directory exists
    if [ ! -d "$src_dir" ]; then
        echo "Source directory not found: $src_dir" >&2
        exit 1
    fi

    # Check if the destination directory exists
    if [ ! -d "$dest_dir" ]; then
        echo "Destination directory not found: $dest_dir" >&2
        exit 1
    fi

    files=$(find "$src_dir" -mindepth 1 -type d | sort -ur)

    # Loop through the files and attempt to create symlinks from source to destination
    while IFS= read -r file; do
        # Remove the source directory prefix from the file path
        relative_path="${file#$src_dir/}"

        # Create a symlink from source to destination, preserving the file path structure
        if ln -sT "$file" "$dest_dir/$relative_path" >/dev/null 2>&1; then
            echo "Symlink created: $dest_dir/$relative_path"
        fi
    done <<< "$files"
}

# show help
help() {
    echo "Usage: ./vortex-linux [command]"
    echo "Commands:"
    echo "  install             Set up dependencies and install Vortex"
    echo "  start               Start Vortex"
    echo "  uninstall           Uninstall Vortex"
    echo "  update              Download the latest Wine, Vortex, and game mappings"
    echo "  symlink             Symlink target game's home subfolders to Vortex"
    echo ""
    echo "Description:"
    echo "  This script allows you to install and run Vortex, a mod manager for games."
    echo "  The script handles the installation and setup of Wine, as well as the"
    echo "  installation of Vortex using Wine."
    echo ""
    echo "Command Details:"
    echo "  install: Set up dependencies and install Vortex"
    echo "    This command sets up the required folders, downloads the latest"
    echo "    version of Wine-GE-Custom, downloads the latest Vortex setup"
    echo "    executable, creates the Vortex Wineprefix, and mounts the"
    echo "    necessary game folders as Windows drives."
    echo ""
    echo "  start: Start Vortex"
    echo "    This command starts Vortex using the specified Wine build."
    echo ""
    echo "  uninstall: Uninstall Vortex"
    echo "    This command removes all Vortex-related files and directories."
    echo ""
    echo "  update: Update to the latest Wine, Vortex, and game mappings"
    echo "    This command downloads the latest versions of Wine-GE-Custom,"
    echo "    Vortex setup executable, and the game mappings file."
    echo ""
    echo "  symlink: Symlink target game's home subfolders to Vortex"
    echo "    This command allows you to symlink the target game's home subfolders"
    echo "    to Vortex. This is useful for games that store configuration files"
    echo "    in their home directory. It helps Vortex manage mods for those games"
    echo "    seamlessly by linking the required folders."
}

if declare -f "$1" >/dev/null; then
    "$@"
    exit 0
else
    help
    exit 1
fi
